version: '3.1'
services:
  node:
    build:
      context: ./quasar
      dockerfile: Dockerfile
    command: sh -c "tail -f /dev/null"
    ports:
      - "3000:3000"
    volumes:
      - ./quasar:/usr/src/app 
      # After init quasar-project replace:
      # - ./node:/usr/src/app/quasar-project
