version: '3.1'
services:
  db:
      image: mysql:8.0
      container_name: db
      # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
      # (this is just an example, not intended to be a production configuration)
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_USER: root1
        MYSQL_PASSWORD: 123
        # MYSQL_DB: db
      ports:
        - "3306:3306"

    phpmyadmin:
      depends_on:
          - db
      image: phpmyadmin/phpmyadmin
      container_name: pma
      hostname: database
      links:
        - db
      restart: always
      environment:
        PMA_PORT: 3306
        # PMA_ARBITRARY - when set to 1 connection to the arbitrary server will be allowed
        # PMA_HOST - define address/host name of the MySQL server
        # PMA_VERBOSE - define verbose name of the MySQL server
        # PMA_PORT - define port of the MySQL server
        # PMA_HOSTS - define comma separated list of address/host names of the MySQL servers
        # PMA_VERBOSES - define comma separated list of verbose names of the MySQL servers
        # PMA_PORTS - define comma separated list of ports of the MySQL servers
        # PMA_USER and PMA_PASSWORD - define username and password to use only with the config authentication method
        # PMA_ABSOLUTE_URI - the full URL to phpMyAdmin. Sometimes needed when used in a reverse-proxy configuration. Don't set this unless needed. See documentation.
        # PMA_CONFIG_BASE64 - if set, this option will override the default config.inc.php with the base64 decoded contents of the variable
        # PMA_USER_CONFIG_BASE64 - if set, this option will override the default config.user.inc.php with the base64 decoded contents of the variable
        # PMA_CONTROLHOST - when set, this points to an alternate database host used for storing the phpMyAdmin Configuration Storage database database
        # PMA_CONTROLPORT - if set, will override the default port (3306) for connecting to the control host for storing the phpMyAdmin Configuration Storage database database
        # PMA_PMADB - define the name of the database to be used for the phpMyAdmin Configuration Storage database. When not set, the advanced features are not enabled by default (they can still potentially be enabled by the user when logging in with the zero conf (zero configuration) feature. Suggested values: phpmyadmin or pmadb
        # PMA_CONTROLUSER - define the username for phpMyAdmin to use for advanced features (the controluser)
        # PMA_CONTROLPASS - define the password for phpMyAdmin to use with the controluser
        # PMA_QUERYHISTORYDB - when set to true, enables storing SQL history to the phpMyAdmin Configuration Storage database. When false, history is stored in the browser and is cleared when logging out
        # PMA_QUERYHISTORYMAX - when set to an integer, controls the number of history items. See documentation. Defaults to 25.
        # MAX_EXECUTION_TIME - if set, will override the maximum execution time in seconds (default 600) for phpMyAdmin ($cfg['ExecTimeLimit']) and PHP max_execution_time (format as [0-9+])
        # MEMORY_LIMIT - if set, will override the memory limit (default 512M) for phpMyAdmin ($cfg['MemoryLimit']) and PHP memory_limit (format as [0-9+](K,M,G))
        # UPLOAD_LIMIT - if set, this option will override the default value for apache and php-fpm (format as [0-9+](K,M,G) default value is 2048K, this will change upload_max_filesize and post_max_size values)
        # HIDE_PHP_VERSION - if defined, this option will hide the PHP version (expose_php = Off). Set to any value (such as HIDE_PHP_VERSION=true).
        # For usage with Docker secrets, appending _FILE to the PMA_PASSWORD environment variable is allowed (it overrides PMA_PASSWORD if it is set):
        # docker run --name myadmin -d -e PMA_PASSWORD_FILE=/run/secrets/db_password.txt -p 8080:80 phpmyadmin
        # Variables that can be read from a file using _FILE
        # PMA_PASSWORD
        # MYSQL_ROOT_PASSWORD
        # MYSQL_PASSWORD
        # PMA_HOSTS
        # PMA_HOST
        # PMA_CONTROLPASS
      ports:
        - 8081:80

    adminer:
      image: adminer  
      restart: always
      ports:
        - 8082:8080 
