version: '3.1'
services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    # command: sh -c "tail -f /dev/null" # command to keep runing the container
    command: sh -c "node app.js" # command to keep runing the container
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app 
